package com.github.mikephil.chartingNIR.listener;

import com.github.mikephil.chartingNIR.dataNIR.DataSet;
import com.github.mikephil.chartingNIR.dataNIR.EntryNIR;

/**
 * Listener for callbacks when drawing on the chart.
 * 
 * @author Philipp
 * 
 */
public interface OnDrawListener {

	/**
	 * Called whenever an entryNIR is added with the finger. Note this is also called for entries that are generated by the
	 * library, when the touch gesture is too fast and skips points.
	 * 
	 * @param entryNIR
	 *            the last drawn entryNIR
	 */
	void onEntryAdded(EntryNIR entryNIR);

	/**
	 * Called whenever an entryNIR is moved by the user after beeing highlighted
	 * 
	 * @param entryNIR
	 */
	void onEntryMoved(EntryNIR entryNIR);

	/**
	 * Called when drawing finger is lifted and the draw is finished.
	 * 
	 * @param dataSet
	 *            the last drawn DataSet
	 */
	void onDrawFinished(DataSet<?> dataSet);

}
